---
# yaml-language-server: $schema=https://www.updatecli.io/schema/latest/config.json
name: Autodiscovery - Action

scms:
  gitops:
    kind: github
    spec:
      owner: a1994sc
      repository: gitops-v2
      token: "{{ requiredEnv .github.token }}"
      branch: main

autodiscovery:
  scmid: gitops
  actionid: github
  groupby: individual
  crawlers:
    github/action:
      digest: true

actions:
  github:
    kind: "github/pullrequest"
    scmid: gitops
    spec:
      automerge: false
      draft: false
      mergemethod: squash
      parent: false
