---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: postgres-operator
  valuesFrom:
    - kind: ConfigMap
      name: hr-values-postgres-operator
      optional: false
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
