---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-operator
resources:
  - helm-release.yml
  - oci-repo.yml
  - namespace.yml
configMapGenerator:
  - name: hr-values-postgres-operator
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
