---
# yaml-language-server: $schema=https://raw.githubusercontent.com/google/yamlfmt/refs/heads/main/schema.json
line_ending: lf
exclude:
- core/fluxcd/manifests
- core/gateway
formatter:
  type: basic
  include_document_start: true
  eof_newline: true
  trim_trailing_whitespace: true
  indentless_arrays: false
