---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ksca
resources:
  - namespace.yml
  - helm-release.yml
  - oci-repo.yml
configMapGenerator:
  - name: ksca-values
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
