---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - helm-repo.yml
  - helm-release.yml
configMapGenerator:
  - name: hr-values-metrics-server
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
