---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-operator
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: chart-proxy-redis-operator
  valuesFrom:
  - kind: ConfigMap
    name: hr-values-redis-operator
    optional: false
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
