---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis-operator
resources:
- helm-release.yml
- oci-repo.yml
configMapGenerator:
- name: hr-values-redis-operator
  files:
  - values.yaml
  options:
    disableNameSuffixHash: true
