---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  interval: 1m
  chart:
    spec:
      chart: metrics-server
      # renovate: datasource=helm depName=metrics-server repository=https://kubernetes-sigs.github.io/metrics-server/
      version: 3.12.2
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: metrics-server-values
      optional: false
