---
fullnameOverride: metrics-server
replicas: 2
affinty:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: k8s-app
              operator: In
              values:
                - "metrics-server"
        topologyKey: kubernetes.io/hostname
tolerations:
  - key: CriticalOnly
    operator: Exists
  - key: InfrastructureOnly
    operator: Exists
resources:
  requests:
    cpu: 100m
    memory: 32Mi
  limits:
    memory: 256Mi
