---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ztunnel
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: istio-ztunnel
  dependsOn:
    - name: istio-istiod
  valuesFrom:
    - kind: ConfigMap
      name: hr-values-istio-ztunnel
      optional: false
