---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-istiod
spec:
  interval: 1m
  chartRef:
    kind: OCIRepository
    name: istio-istiod
  dependsOn:
    - name: istio-cni
  valuesFrom:
    - kind: ConfigMap
      name: hr-values-istio-istiod
      optional: false
  values:
    profile: ambient
