---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kyverno
resources:
  - namespace.yml
  - helm-release.yml
  - oci-repo.yml
configMapGenerator:
  - name: kyverno-values
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
