---
package:
  create:
    skip_sbom: false
    set:
      agent_image_domain: ghcr.io/
      agent_image: zarf-dev/zarf/agent
      agent_image_tag: v0.45.0
      injector_version: "2024-07-22"
      injector_amd64_shasum: 8463bfd66930a4b26c665b51f25e8a32ed5948068bae49987013c89173394478
      injector_arm64_shasum: b905e647e0d7876cfd5b665632cfc43ad919dc60408f7236c5b541c53277b503
      registry_image_domain: docker.io
      registry_image: library/registry
      registry_image_tag: 2.8.3
      gitea_image: docker.io/gitea/gitea:1.23.6-rootless
