---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm-release.yml
- oci-repo.yml
configMapGenerator:
- name: hr-values-istio-cni
  namespace: istio-system
  files:
  - values.yaml
  options:
    disableNameSuffixHash: true
