---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yml
patches:
# Multi-Tenant hardening
- target:
    kind: Deployment
    name: "(kustomize-controller|helm-controller|notification-controller|image-reflector-controller|image-automation-controller)"
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --no-cross-namespace-refs=true
- target:
    kind: Deployment
    name: "kustomize-controller"
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --no-remote-bases=true
- target:
    kind: Deployment
    name: "(kustomize-controller|helm-controller)"
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --default-service-account=default
- target:
    kind: Kustomization
    name: "flux-system"
  patch: |
    - op: add
      path: /spec/serviceAccountName
      value: kustomize-controller
# CIS hardening
- target:
    kind: ServiceAccount
    labelSelector: app.kubernetes.io/part-of=flux
  patch: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: all
    automountServiceAccountToken: false
- target:
    kind: Deployment
    labelSelector: app.kubernetes.io/part-of=flux
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: whatever
    spec:
      template:
        metadata:
          annotations:
            # Required by Kubernetes node autoscaler
            cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        spec:
          terminationGracePeriodSeconds: 60
          automountServiceAccountToken: true
          # Required by Pod Security Policy
          securityContext:
            runAsUser: 1000
            fsGroup: 1000
          containers:
            - name: manager
              # Required by Pod Security Policy
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                privileged: false
                readOnlyRootFilesystem: true
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                capabilities:
                  drop:
                    - ALL
                $patch: replace
# Increase how many resources flux will reconcile at once
- target:
    kind: Deployment
    name: helm-controller
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --concurrent=10
- target:
    kind: Deployment
    name: kustomize-controller
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --concurrent=10
