---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
resources:
- helm-release.yml
- namespace.yml
- oci-repo.yml
configMapGenerator:
- name: rook-ceph-operator-values
  files:
  - values.yaml
  options:
    disableNameSuffixHash: true
