---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
resources:
  - helm-release.yml
  - namespace.yml
  - oci-repo.yml
configMapGenerator:
  - name: hr-values-rook-ceph-operator
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
