---
hub: docker.io/istio
variant: "distroless"
image: ztunnel
labels: {}
volumeMounts: []
volumes: []
podAnnotations:
  prometheus.io/port: "15020"
  prometheus.io/scrape: "true"
podLabels: {}
resources:
  requests:
    cpu: 200m
    # Ztunnel memory scales with the size of the cluster and traffic load
    # While there are many factors, this is enough for ~200k pod cluster or 100k concurrently open connections.
    memory: 512Mi
istioNamespace: istio-system
logLevel: info
seLinuxOptions:
  type: spc_t
