---
name: Daily Image Cleanup
on:
  # every day at 01:30am
  schedule:
    - cron: '30 1 * * *'
  # or manually
  workflow_dispatch:
jobs:
  ghcr-cleanup-image:
    name: ghcr cleanup action
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
        with:
          packages: gitops/core
          include-tags: "^v?([0-9]+\\.){2}[0-9]+-[0-9]+-.{8}$"
          keep-n-tagged: 10
          delete-untagged: true
          delete-orphaned-images: true
          use-regex: true
